plugins {
    id 'java-library'
    id 'maven-publish'
    id 'fabric-loom' version '1.15.2'
    id 'idea'
}

version = mod_version
group = mod_group_id

base {
    archivesName = mod_id
}

repositories {
    maven { url = 'https://maven.fabricmc.net/' }
}

dependencies {
    minecraft "com.mojang:minecraft:${minecraft_version}"
    mappings loom.officialMojangMappings()
    modImplementation "net.fabricmc:fabric-loader:${loader_version}"
}

loom {
    accessWidenerPath = file("src/main/resources/paxels.accesswidener")
}

def targetJavaVersion = minecraft_version == '1.20.1' ? 17 : (minecraft_version.startsWith('26.') ? 25 : 21)
java.toolchain.languageVersion = JavaLanguageVersion.of(targetJavaVersion)

sourceSets.main.resources {
    srcDir('src/generated/resources')
    exclude("**/*.bbmodel")
    exclude("src/generated/**/.cache")
    exclude("META-INF/neoforge.mods.toml")
}

tasks.named('jar', Jar).configure {
    archiveFileName = "${mod_id}-${mod_version}-fabric-${minecraft_version}.jar"
}

tasks.named('remapJar').configure {
    archiveFileName = "${mod_id}-${mod_version}-fabric-${minecraft_version}.jar"
}

tasks.register('copyReleaseJar', Copy) {
    dependsOn tasks.named('remapJar')
    from(tasks.named('remapJar').flatMap { it.archiveFile })
    into(layout.projectDirectory.dir("release-jars/fabric/${mod_version}"))
}

tasks.named('build') {
    finalizedBy tasks.named('copyReleaseJar')
}

tasks.withType(ProcessResources).configureEach {
    var replaceProperties = [
            minecraft_version: minecraft_version,
            loader_version   : loader_version,
            mod_id           : mod_id,
            mod_name         : mod_name,
            mod_license      : mod_license,
            mod_version      : mod_version,
            mod_authors      : mod_authors,
            mod_description  : mod_description,
            target_java_version: targetJavaVersion,
    ]
    inputs.properties replaceProperties

    filesMatching(['fabric.mod.json']) {
        expand replaceProperties
    }
}

publishing {
    publications {
        register('mavenJava', MavenPublication) {
            from components.java
        }
    }
    repositories {
        maven {
            url "file://${project.projectDir}/repo"
        }
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
    options.release = targetJavaVersion
}

idea {
    module {
        downloadSources = true
        downloadJavadoc = true
    }
}
